name: Publish PyShamir dist 📦 to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and publish PyShamir dist 📦
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compute version
        id: compute_version
        run: echo "version=$(echo ${{ github.ref_name }} | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')" >>${GITHUB_OUTPUT}
      - name: Setup Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload dist 📦 to release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: pyshamir-${{ steps.compute_version.outputs.version }}.tar.gz
          asset_path: ./dist/pyshamir-${{ steps.compute_version.outputs.version }}.tar.gz
          asset_content_type: application/gzip
      - name: Publish dist 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
